name: Deployment Pipeline

on:
  push:
  workflow_dispatch:

jobs:

  version:
    name: Version
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - id: git-version
        uses: codacy/git-version@2.5.4
        with:
          release-branch: ${{ github.event.repository.default_branch }}
          minor-identifier: 'minor'
          major-identifier: 'major'
          prefix: v

      - id: create-release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.git-version.outputs.version }}
          release_name: ${{ steps.git-version.outputs.version }}
          body: ${{ github.event.head_commit.message }}
          draft: false 
          prerelease: false

    outputs:
      version: ${{ steps.git-version.outputs.version }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - uses: actions/checkout@v3
    
      - id: node-version
        run: echo "version=$(cat .node-version)" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node-version.outputs.version }}
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - uses: aws-actions/amazon-ecr-login@v1

      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: 573536211534.dkr.ecr.eu-west-2.amazonaws.com/${{ github.event.repository.name }}:${{ needs.version.outputs.version }}
          provenance: false

      - shell: bash
        run: sed -i 's/VERSION_PLACEHOLDER/${{ needs.version.outputs.version }}/' ./cloudformation/stack.yaml

      - run: aws s3 sync ./cloudformation s3://zonumi-cloudformation/${{ github.event.repository.name }}/${{ needs.version.outputs.version }}

  deploy-playground:
    name: Deploy playground
#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [ version, build ]
    steps:
      - uses: magnetikonline/action-golang-cache@v3
        with:
          go-version: 1.19.5

      - run: go install github.com/aws-cloudformation/rain/cmd/rain@main

      - run: >
          export GOPATH="$HOME/go"
          export PATH="$GOPATH/bin:$PATH"

      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::509744907983:role/OrganizationAccountAccessRole
          role-duration-seconds: 1200

      - run: aws s3 cp s3://zonumi-cloudformation/${{ github.event.repository.name }}/${{ needs.version.outputs.version }} ./cloudformation --recursive

      - run: >
          rain deploy \
          --yes --debug \
          cloudformation/stack.yaml zonumi-website \
          --config cloudformation/playground.params.json \
          --role-arn arn:aws:iam::509744907983:role/CloudformationDeveloperRole \
          --region eu-west-2

#      - run: aws cloudformation deploy --template-file ./cloudformation/stack.yaml --stack-name ${{ github.event.repository.name }} --parameter-overrides VpcName=playground --capabilities CAPABILITY_IAM

#      - run: aws s3 sync ./out s3://${{ github.event.repository.name }}
#        if: github.event_name == 'push' && github.ref == 'refs/heads/main'