name: Deployment Pipeline

on: [push]

jobs:

  version:
    name: Version
    runs-on: ubuntu-latest
    permissions: 
      contents: write  
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - id: git-version
        uses: codacy/git-version@2.5.4
        with:
          release-branch: ${{ github.event.repository.default_branch }}
          minor-identifier: 'minor'
          major-identifier: 'major'
          prefix: v
      
      - id: create-release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.git-version.outputs.version }} 
          release_name: ${{ steps.git-version.outputs.version }} 
          body: ${{ github.event.head_commit.message }} 
          draft: false 
          prerelease: false