name: Deployment Pipeline

on: [push]

jobs:

  version:
    name: Checkout
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - id: Version
        uses: codacy/git-version@2.5.4
        with:
          release-branch: ${{ github.event.repository.default_branch }}
          minor-identifier: 'minor'
          major-identifier: 'major'
          preview: v
      